/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xyzhostelmanagementsystem;

import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.util.Date;
import xyzhostelmanagementsystem.Payment;

/**
 *
 * @author Killi
 */
public class HostelApplicationForm extends javax.swing.JFrame {

    File f = new File("C:\\Users\\Killi\\OneDrive\\桌面\\Java Assigment");
    int in;
    String ID, Name, Course, Email, Intake, Age, Address, Status, RoomType, RoomPrice;

    public HostelApplicationForm() {
        initComponents();
        jComboBox2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String selectedRoomID = (String) jComboBox2.getSelectedItem();
                importData("C:\\Users\\Killi\\OneDrive\\桌面\\Java Assigment", selectedRoomID);
            }
        });
    }

    void readFile() {
        FileReader fr = null;
        try {
            fr = new FileReader(f + "\\FormSub.txt");
            System.err.println("file exists!");
        } catch (FileNotFoundException ex) {
            try {
                FileWriter fw = new FileWriter(f + "\\FormSub.txt");
                System.out.println("File Created");
            } catch (IOException ex1) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    void importData(String file, String roomID) {
        try {
            FileReader fr = new FileReader(file + "\\Room Details.txt");
            BufferedReader br = new BufferedReader(fr);
            String line;
            String specificData = "";

            // Loop through the lines in the text file
            while ((line = br.readLine()) != null) {
                String[] columns = line.split(",");

                String currentRoomID = columns[0];

                if (currentRoomID.equals(roomID)) {
                    String specificColumn1 = columns[1]; // Room Type
                    String specificColumn2 = columns[4]; // Room Price

                    TXT2.setText(specificColumn1);
                    TXT1.setText(specificColumn2);

                    // Write the specific column values into another text file
                    // Exit the loop since the desired room ID is found
                    break;
                }
            }

            // Close the file readers
            br.close();
            fr.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String[] getDataFromForm1() {
        String[] formData = new String[9];
        formData[0] = J1.getText();
        formData[1] = J2.getText();
        formData[2] = J3.getText();
        formData[3] = J4.getText();
        formData[4] = J5.getText();
        formData[5] = J6.getText();
        formData[7] = TXT1.getText();
        formData[8] = TXT2.getText();

        return formData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        J5 = new javax.swing.JTextField();
        J1 = new javax.swing.JTextField();
        J2 = new javax.swing.JTextField();
        J6 = new javax.swing.JTextField();
        J3 = new javax.swing.JTextField();
        J4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        TXT1 = new javax.swing.JTextField();
        TXT2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 480));
        jPanel1.setLayout(null);

        jLabel1.setText("Student Name:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 100, 90, 14);

        jLabel2.setText("Intake:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 340, 90, 14);

        jLabel3.setText("Age:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 160, 90, 14);

        jLabel4.setText("Course:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 240, 90, 14);

        jLabel5.setText("Email:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(470, 90, 80, 14);

        jLabel6.setText("Prefered Room Number:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(410, 230, 170, 14);

        jLabel7.setText("Address:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(470, 170, 80, 14);
        jPanel1.add(J5);
        J5.setBounds(560, 160, 200, 40);
        jPanel1.add(J1);
        J1.setBounds(180, 80, 200, 40);
        jPanel1.add(J2);
        J2.setBounds(180, 230, 200, 40);
        jPanel1.add(J6);
        J6.setBounds(180, 150, 200, 40);
        jPanel1.add(J3);
        J3.setBounds(560, 80, 200, 40);
        jPanel1.add(J4);
        J4.setBounds(180, 330, 200, 40);

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(600, 350, 130, 50);

        jButton3.setText("Next");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(420, 350, 130, 50);

        jLabel8.setText("Room Type:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(470, 270, 80, 14);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HR1", "HR2", "HR3", "HR4", "HR5", "HR6", "HR7", "HR8" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(560, 230, 200, 20);

        jLabel13.setText("Room Price:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(470, 310, 120, 14);
        jPanel1.add(TXT1);
        TXT1.setBounds(560, 310, 200, 20);
        jPanel1.add(TXT2);
        TXT2.setBounds(560, 270, 200, 20);

        jLabel9.setText("Student Application Form");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(340, 30, 130, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        ID = J1.getText();
        Course = J2.getText();
        Email = J3.getText();
        Intake = J4.getText();
        Age = J6.getText();
        Address = J5.getText();
        RoomType = TXT2.getText();
        RoomPrice = TXT1.getText();
        String[] formData = getDataFromForm1();
//Functions         
        readFile();

//Data Validation
       if (ID.equals("")) {
    JOptionPane.showMessageDialog(null, "ID is mandatory.");
} else if (Course.equals("")) {
    JOptionPane.showMessageDialog(null, "Course is mandatory.");
} else if (Email.equals("")) {
    JOptionPane.showMessageDialog(null, "Email is mandatory.");
} else if (Intake.equals("")) {
    JOptionPane.showMessageDialog(null, "Intake is mandatory.");
} else if (Age.equals("")) {
    JOptionPane.showMessageDialog(null, "Age is mandatory.");
} else if (Address.equals("")) {
    JOptionPane.showMessageDialog(null, "Address is mandatory.");
} else if (!Age.matches("\\d+")) {
    // Validate the age field using regex to ensure it contains only digits
    JOptionPane.showMessageDialog(null, "Invalid age. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
} else if (!Email.matches("[\\w.]+@[\\w.]+\\.\\w+")) {
    // Validate the email field using regex to ensure it has a valid email format
    JOptionPane.showMessageDialog(null, "Invalid email address. Please enter a valid email.", "Error", JOptionPane.ERROR_MESSAGE);
} else if (Address.length() < 5) {
    // Validate the address field to ensure it has a minimum length of 5 characters
    JOptionPane.showMessageDialog(null, "Invalid address. Please enter a valid address.", "Error", JOptionPane.ERROR_MESSAGE);
} else if (!Course.matches("[A-Za-z\\s]+")) {
    // Validate the course field using regex to ensure it contains only alphabets and spaces
    JOptionPane.showMessageDialog(null, "Invalid course name. Please enter a valid course.", "Error", JOptionPane.ERROR_MESSAGE);
        // Validate the course field using regex to ensure it contains only alphabets and spaces
        JOptionPane.showMessageDialog(this, "Invalid course name. Please enter a valid course.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
         Payment paymentForm = new Payment(formData);
            paymentForm.setVisible(true);
              this.dispose();
            JOptionPane.showMessageDialog(this, "Data Successfully Submitted!!");
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        J1.setText("");
        J2.setText("");
        J3.setText("");
        J4.setText("");
        J5.setText("");
        J6.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HostelApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HostelApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HostelApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HostelApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HostelApplicationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField J1;
    private javax.swing.JTextField J2;
    private javax.swing.JTextField J3;
    private javax.swing.JTextField J4;
    private javax.swing.JTextField J5;
    private javax.swing.JTextField J6;
    private javax.swing.JTextField TXT1;
    private javax.swing.JTextField TXT2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
