
package hostelmanagementsystem.Admin;

import javax.swing.ImageIcon;


public class AboutUs extends javax.swing.JFrame {

    ImageIcon LPbg = new ImageIcon("landingpage_bg.png");
    ImageIcon wi = new ImageIcon("thelogo.jpg");
        
    public AboutUs() {
        initComponents();
        this.setSize(585, 385);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        BgPic1.setText("");
        BgPic1.setIcon(LPbg);
        
        // Window itself
        this.setTitle("About Us | XYZ Hostel Management");
        this.setIconImage(wi.getImage());
        
        // Window when close
        this.setDefaultCloseOperation(LandingPage.EXIT_ON_CLOSE);
        this.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        BackClick = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BgPic1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("AboutUs"); // NOI18N
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 192, 244));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 338, 600, 50);

        jPanel1.setBackground(new java.awt.Color(102, 192, 244));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(560, 0, 40, 390);

        jScrollPane1.setToolTipText("");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(42, 71, 94));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(199, 213, 224));
        jTextArea1.setRows(5);
        jTextArea1.setText("XYZ hostel is an excellent option for students who are looking for affordable \naccommodation in a convenient location. \n\nThe hostel is specifically designed to cater to the needs of students.\n\nWe offer a range of amenities and services that make it a popular choice among \nthe student community.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 120, 500, 190);

        BackClick.setFont(new java.awt.Font("Kanit SemiBold", 0, 14)); // NOI18N
        BackClick.setForeground(new java.awt.Color(255, 255, 255));
        BackClick.setText("<< BACK");
        BackClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackClickMouseClicked(evt);
            }
        });
        getContentPane().add(BackClick);
        BackClick.setBounds(20, 20, 70, 30);

        jLabel3.setFont(new java.awt.Font("Kanit SemiBold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ABOUT XYZ HOSTEL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 40, 350, 60);

        BgPic1.setToolTipText("XYZ hostel background");
        BgPic1.setMaximumSize(new java.awt.Dimension(585, 385));
        BgPic1.setMinimumSize(new java.awt.Dimension(585, 385));
        BgPic1.setName("BgPic1"); // NOI18N
        BgPic1.setPreferredSize(new java.awt.Dimension(585, 385));
        getContentPane().add(BgPic1);
        BgPic1.setBounds(0, 0, 585, 385);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackClickMouseClicked
        LandingPage lp = new LandingPage();
        lp.setLocationRelativeTo(null);
        lp.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackClickMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackClick;
    private javax.swing.JLabel BgPic1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
