package hostelmanagementsystem.Admin;

import hostelmanagementsystem.Students.ManagerSAP;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

public class AdminMainMenu extends javax.swing.JFrame {

    ImageIcon AMI = new ImageIcon("AdminMenuIcon.jpg");
    ImageIcon wi = new ImageIcon("thelogo.jpg");

    private UserSession userSession;

    public AdminMainMenu(UserSession userSession) {

        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        AdminMenuIcon.setText("");
        AdminMenuIcon.setIcon(AMI);

        // Window itself
        this.setTitle("Admin Main Menu | XYZ Hostel Management");
        this.setIconImage(wi.getImage());
        this.setSize(750, 455);

        // Window when close
        this.setDefaultCloseOperation(LandingPage.EXIT_ON_CLOSE);
        this.setVisible(false);

        // Get And Set Username
        this.userSession = userSession;
        String uppercaseUsername = userSession.username.toUpperCase();
        adminNameDis.setText(uppercaseUsername);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        HAManagement1 = new javax.swing.JButton();
        GReport = new javax.swing.JButton();
        HRInformation = new javax.swing.JButton();
        CSRecord = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        AdminMenuIcon = new javax.swing.JLabel();
        adminNameDis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("AdminMainMenu"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Kanit SemiBold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("WELCOME BACK, ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 40, 210, 20);

        HAManagement1.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        HAManagement1.setText("H.A. Management");
        HAManagement1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAManagement1ActionPerformed(evt);
            }
        });
        getContentPane().add(HAManagement1);
        HAManagement1.setBounds(40, 90, 270, 50);

        GReport.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        GReport.setText("Generate Reports");
        GReport.setToolTipText("");
        GReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GReportActionPerformed(evt);
            }
        });
        getContentPane().add(GReport);
        GReport.setBounds(40, 330, 270, 50);

        HRInformation.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        HRInformation.setText("Hostel Room Information");
        HRInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HRInformationActionPerformed(evt);
            }
        });
        getContentPane().add(HRInformation);
        HRInformation.setBounds(40, 170, 270, 50);

        CSRecord.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        CSRecord.setText("Check Student's Record");
        CSRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSRecordActionPerformed(evt);
            }
        });
        getContentPane().add(CSRecord);
        CSRecord.setBounds(40, 250, 270, 50);

        jPanel5.setBackground(new java.awt.Color(73, 209, 163));
        jPanel5.setForeground(new java.awt.Color(74, 113, 209));
        jPanel5.setLayout(null);

        btnBack.setFont(new java.awt.Font("Kanit Medium", 2, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel5.add(btnBack);
        btnBack.setBounds(580, 40, 100, 40);

        AdminMenuIcon.setPreferredSize(new java.awt.Dimension(750, 455));
        jPanel5.add(AdminMenuIcon);
        AdminMenuIcon.setBounds(410, 120, 310, 260);

        adminNameDis.setFont(new java.awt.Font("Kanit SemiBold", 0, 18)); // NOI18N
        adminNameDis.setForeground(new java.awt.Color(255, 204, 51));
        jPanel5.add(adminNameDis);
        adminNameDis.setBounds(190, 50, 130, 20);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, -10, 760, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GReportActionPerformed
        UserSession userSession = new UserSession("admin"); // Create UserSession instance with username
        AdminGenerateReports agr = new AdminGenerateReports(userSession);
        agr.setLocationRelativeTo(null);
        agr.setVisible(true);
        dispose();

//        generateIR agr = new generateIR();
//        agr.setLocationRelativeTo(null); 
//        agr.setVisible(true);
//        dispose(); 
    }//GEN-LAST:event_GReportActionPerformed

    private void HRInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HRInformationActionPerformed
        try {
            UserSession userSession = new UserSession("admin"); // Create UserSession instance with username
            AdminHRI hri = new AdminHRI(userSession);
            hri.setLocationRelativeTo(null);
            hri.setVisible(true);
            dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_HRInformationActionPerformed

    private void CSRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSRecordActionPerformed
        UserSession userSession = new UserSession("admin"); // Create UserSession instance with username
        CheckStudentRecord csr = new CheckStudentRecord(userSession);
        csr.setLocationRelativeTo(null);
        csr.setVisible(true);
        dispose();
    }//GEN-LAST:event_CSRecordActionPerformed

    private void HAManagement1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAManagement1ActionPerformed
        ManagerSAP ms = new ManagerSAP(userSession);
        ms.setLocationRelativeTo(null);
        ms.setVisible(true);
        dispose();
    }//GEN-LAST:event_HAManagement1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminLogin al = new AdminLogin();
        al.setLocationRelativeTo(null);
        al.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserSession userSession = new UserSession("admin"); // Create UserSession instance with username
                new AdminMainMenu(userSession).setVisible(true); // Pass UserSession instance to the constructor
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminMenuIcon;
    private javax.swing.JButton CSRecord;
    private javax.swing.JButton GReport;
    private javax.swing.JButton HAManagement1;
    private javax.swing.JButton HRInformation;
    private javax.swing.JLabel adminNameDis;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
