/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostelmanagementsystem.Admin;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class AdminLogin extends javax.swing.JFrame implements FilesLocation {

    ImageIcon ALbg = new ImageIcon("adminlogin_icon.png");
    ImageIcon wi = new ImageIcon("thelogo.jpg");

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {

        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        BgPic1.setText("");
        BgPic1.setIcon(ALbg);

        // Window itself
        this.setTitle("Admin Login | XYZ Hostel Management");
        this.setSize(800, 475);

        //Window itself
        this.setIconImage(wi.getImage());

        // Window when close
        this.setDefaultCloseOperation(LandingPage.EXIT_ON_CLOSE);
        this.setVisible(false);

        // Forgot Password Text
        String fp = "<HTML><u>FORGOT PASSWORD</u></HTML>";
        lblForgotPassword.setText(fp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        BgPic1 = new javax.swing.JLabel();
        lblForgotPassword = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pfpPassword = new javax.swing.JPasswordField();
        cbShowPassword = new javax.swing.JCheckBox();
        btnLogin = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BackBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(19, 139, 221));
        setForeground(new java.awt.Color(19, 139, 221));
        setMinimumSize(new java.awt.Dimension(800, 480));
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(102, 194, 244));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 440, 810, 60);

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(91, 196, 255));
        jLabel2.setText("USERNAME:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 160, 100, 32);

        jPanel2.setBackground(new java.awt.Color(45, 78, 98));
        jPanel2.setName("AdminLogin"); // NOI18N
        jPanel2.setLayout(null);

        txtUsername.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtUsername.setToolTipText("Enter Your Usernme");
        txtUsername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsername);
        txtUsername.setBounds(170, 170, 190, 40);
        jPanel2.add(BgPic1);
        BgPic1.setBounds(40, 70, 60, 60);

        lblForgotPassword.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        lblForgotPassword.setForeground(new java.awt.Color(199, 213, 224));
        lblForgotPassword.setText("FORGOT PASSWORD?");
        lblForgotPassword.setToolTipText("");
        lblForgotPassword.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgotPasswordMouseClicked(evt);
            }
        });
        jPanel2.add(lblForgotPassword);
        lblForgotPassword.setBounds(50, 305, 120, 21);

        jLabel5.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(67, 218, 218));
        jLabel5.setText("_____________________________________");
        jLabel5.setToolTipText("");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 20, 340, 60);

        jLabel6.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("WELCOME BACK TO");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(160, 70, 130, 20);

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("_________________________________");
        jLabel7.setToolTipText("");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 100, 330, 60);

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("ADMIN LOGIN");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(110, 80, 230, 60);

        jLabel9.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("_____________________________________");
        jLabel9.setToolTipText("");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(40, 100, 340, 60);

        pfpPassword.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        pfpPassword.setToolTipText("Enter Your Password");
        pfpPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(pfpPassword);
        pfpPassword.setBounds(170, 240, 190, 40);

        cbShowPassword.setBackground(new java.awt.Color(102, 194, 244));
        cbShowPassword.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        cbShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        cbShowPassword.setText("SHOW PASSWORD");
        cbShowPassword.setToolTipText("Check This Box To Display Password");
        cbShowPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbShowPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(cbShowPassword);
        cbShowPassword.setBounds(210, 300, 160, 30);

        btnLogin.setFont(new java.awt.Font("Kanit SemiBold", 3, 18)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin);
        btnLogin.setBounds(120, 360, 170, 60);
        btnLogin.getAccessibleContext().setAccessibleName("");

        jLabel11.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(91, 196, 255));
        jLabel11.setText("PASSWORD:");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel11);
        jLabel11.setBounds(60, 240, 110, 32);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(400, -10, 430, 500);

        jPanel1.setBackground(new java.awt.Color(218, 232, 242));
        jPanel1.setLayout(null);

        BackBtn.setFont(new java.awt.Font("Kanit Medium", 2, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn);
        BackBtn.setBounds(10, 10, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\Documents\\NetBeansProjects\\HostelManagementSystem\\adminimage2.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, -10, 450, 500);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 490);

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(91, 196, 255));
        jLabel4.setText("USERNAME:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 160, 100, 32);

        jLabel10.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(91, 196, 255));
        jLabel10.setText("USERNAME:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(460, 160, 100, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUsername.getText();
        String password = pfpPassword.getText();
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

        try {
            File f = new File(FilesLocation.ADMIN_DATABASE);
            Scanner s = new Scanner(f);
            s.useDelimiter("[, \n]");

            // Validate Is Admin Or Not.
            boolean isAdmin = false;

            while (s.hasNext()) {
                String username_db = s.next();
                String password_db = s.next();

                if (username.equals(username_db.trim()) && password.equals(password_db.trim())) {
                    isAdmin = true;
                    JOptionPane.showMessageDialog(null, "Login Success!", "Success", JOptionPane.INFORMATION_MESSAGE);

                    // Record login time
                    FileWriter writer = new FileWriter(FilesLocation.ADMIN_LOGIN_RECORDS);
                    writer.write("Username: " + username + "\n");
                    writer.write("Successfully Authorized As Admin! \n");
                    writer.write("Login Time: " + now.format(formatter) + "\n");
                    writer.close();

                    UserSession userSession = new UserSession(username); // Create UserSession instance
                    AdminMainMenu amm = new AdminMainMenu(userSession); // Pass UserSession instance to AdminMainMenu
                    amm.setVisible(true);
                    this.dispose();

                } else {
                    isAdmin = false;
                    JOptionPane.showMessageDialog(null, "Invalid Input! Please try again.", "Error", JOptionPane.ERROR_MESSAGE);

                    // Record login time
                    FileWriter writer = new FileWriter("admin_login_records.txt", true);
                    writer.write("Username: " + username + "\n");
                    writer.write("Authorization Invalid! \n");
                    writer.write("Login Time: " + now.format(formatter) + "\n");
                    writer.close();
                }

            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException ex) {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        LandingPage lp = new LandingPage();
        lp.setLocationRelativeTo(null);
        lp.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void cbShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPasswordActionPerformed
        String check_pass = new String(pfpPassword.getPassword());
        if (cbShowPassword.isSelected()) {
            pfpPassword.setEchoChar((char) 0);
        } else if (!(cbShowPassword.isSelected()) & (check_pass.equals("") | check_pass.equals("Enter the password..."))) {
            pfpPassword.setEchoChar((char) 0);
        } else {
            pfpPassword.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_cbShowPasswordActionPerformed

    private void lblForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPasswordMouseClicked
        ForgotPassword fp = new ForgotPassword();
        fp.setLocationRelativeTo(null);
        fp.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblForgotPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel BgPic1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox cbShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JPasswordField pfpPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
