/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostelmanagementsystem.Admin;

import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class AdminGenerateReports extends javax.swing.JFrame {

    /**
     * Creates new form AdminGenerateReports
     */
    ImageIcon wi = new ImageIcon("thelogo.jpg");
    private UserSession userSession;

    public AdminGenerateReports(UserSession userSession) {

        //Define User Session
        this.userSession = userSession;

        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);

        //Window itself
        this.setIconImage(wi.getImage());
        this.setTitle("Admin CRUD HRI | XYZ Hostel Management");

        // Window when close
        this.setDefaultCloseOperation(LandingPage.EXIT_ON_CLOSE);
        this.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCRUDtitle = new javax.swing.JLabel();
        btnGenerateMonthlyReports = new javax.swing.JButton();
        btnCalculateData = new javax.swing.JButton();
        btnGeneraterRoomReports = new javax.swing.JButton();
        btnQuickMonthlyReport = new javax.swing.JButton();
        btnBackAGR = new javax.swing.JButton();
        lblAdminGenerateReports = new javax.swing.JLabel();
        btbRandomizedAGR = new javax.swing.JButton();
        btnExitARR1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(67, 110, 204));
        jPanel1.setLayout(null);

        lblCRUDtitle.setFont(new java.awt.Font("Kanit SemiBold", 0, 24)); // NOI18N
        lblCRUDtitle.setForeground(new java.awt.Color(242, 244, 245));
        lblCRUDtitle.setText("XYZ HOSTEL ADMIN MANAGEMENT");
        lblCRUDtitle.setName("AdminHRI"); // NOI18N
        jPanel1.add(lblCRUDtitle);
        lblCRUDtitle.setBounds(200, 50, 390, 30);

        btnGenerateMonthlyReports.setFont(new java.awt.Font("Kanit Medium", 2, 18)); // NOI18N
        btnGenerateMonthlyReports.setText("Generate Monthly Report");
        btnGenerateMonthlyReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerateMonthlyReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateMonthlyReportsActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerateMonthlyReports);
        btnGenerateMonthlyReports.setBounds(60, 160, 270, 80);

        btnCalculateData.setFont(new java.awt.Font("Kanit Medium", 2, 18)); // NOI18N
        btnCalculateData.setText("Calculate Data");
        btnCalculateData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalculateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateDataActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalculateData);
        btnCalculateData.setBounds(350, 250, 190, 80);

        btnGeneraterRoomReports.setFont(new java.awt.Font("Kanit Medium", 2, 18)); // NOI18N
        btnGeneraterRoomReports.setText("Generate Room Report");
        btnGeneraterRoomReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGeneraterRoomReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneraterRoomReportsActionPerformed(evt);
            }
        });
        jPanel1.add(btnGeneraterRoomReports);
        btnGeneraterRoomReports.setBounds(60, 250, 270, 80);

        btnQuickMonthlyReport.setFont(new java.awt.Font("Kanit Medium", 2, 18)); // NOI18N
        btnQuickMonthlyReport.setText("Quick Month Report");
        btnQuickMonthlyReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuickMonthlyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickMonthlyReportActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuickMonthlyReport);
        btnQuickMonthlyReport.setBounds(210, 370, 230, 40);

        btnBackAGR.setFont(new java.awt.Font("Kanit Medium", 2, 18)); // NOI18N
        btnBackAGR.setText("Back");
        btnBackAGR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackAGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAGRActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackAGR);
        btnBackAGR.setBounds(20, 370, 130, 40);

        lblAdminGenerateReports.setFont(new java.awt.Font("Kanit SemiBold", 0, 48)); // NOI18N
        lblAdminGenerateReports.setForeground(new java.awt.Color(145, 178, 246));
        lblAdminGenerateReports.setText("Admin Generate Reports");
        lblAdminGenerateReports.setName("AdminHRI"); // NOI18N
        jPanel1.add(lblAdminGenerateReports);
        lblAdminGenerateReports.setBounds(40, 70, 560, 60);

        btbRandomizedAGR.setFont(new java.awt.Font("Kanit Medium", 2, 18)); // NOI18N
        btbRandomizedAGR.setText("Random Choose");
        btbRandomizedAGR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btbRandomizedAGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbRandomizedAGRActionPerformed(evt);
            }
        });
        jPanel1.add(btbRandomizedAGR);
        btbRandomizedAGR.setBounds(350, 160, 190, 80);

        btnExitARR1.setFont(new java.awt.Font("Kanit Medium", 2, 18)); // NOI18N
        btnExitARR1.setText("Exit");
        btnExitARR1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExitARR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitARR1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnExitARR1);
        btnExitARR1.setBounds(480, 370, 130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateMonthlyReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateMonthlyReportsActionPerformed
        new generateIR(userSession).setVisible(true);
    }//GEN-LAST:event_btnGenerateMonthlyReportsActionPerformed

    private void btnCalculateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateDataActionPerformed
        try {
            CalculateGRI calculator = new CalculateGRI();
            calculator.run();
            JOptionPane.showMessageDialog(null, "Calculated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(AdminGenerateReports.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Failed to calculate.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalculateDataActionPerformed

    private void btnGeneraterRoomReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneraterRoomReportsActionPerformed
        generateRR grr = new generateRR(userSession);
        grr.setLocationRelativeTo(null);
        grr.setVisible(true);
    }//GEN-LAST:event_btnGeneraterRoomReportsActionPerformed

    private void btnQuickMonthlyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickMonthlyReportActionPerformed
        QuickMonthReport qmr = new QuickMonthReport(userSession); // Pass the UserSession instance
        qmr.setLocationRelativeTo(null);
        qmr.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQuickMonthlyReportActionPerformed

    private void btnBackAGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAGRActionPerformed
        AdminMainMenu amm = new AdminMainMenu(userSession); // Pass the UserSession instance
        amm.setLocationRelativeTo(null);
        amm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackAGRActionPerformed

    private void btbRandomizedAGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbRandomizedAGRActionPerformed
        // Generate a random number to determine which frame to display
        int randomNumber = (int) (Math.random() * 2);  // Generates either 0 or 1

        if (randomNumber == 0) {
            // Display generateIR frame
            generateIR gir = new generateIR(userSession);
            gir.setLocationRelativeTo(null);
            gir.setVisible(true);
        } else {
            // Display generateRR frame
            generateRR grr = new generateRR(userSession);
            grr.setLocationRelativeTo(null);
            grr.setVisible(true);
        }
    }//GEN-LAST:event_btbRandomizedAGRActionPerformed

    private void btnExitARR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitARR1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitARR1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGenerateReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGenerateReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGenerateReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGenerateReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserSession userSession = new UserSession("admin"); // Create UserSession instance with username
                new AdminGenerateReports(userSession).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbRandomizedAGR;
    private javax.swing.JButton btnBackAGR;
    private javax.swing.JButton btnCalculateData;
    private javax.swing.JButton btnExitARR1;
    private javax.swing.JButton btnGenerateMonthlyReports;
    private javax.swing.JButton btnGeneraterRoomReports;
    private javax.swing.JButton btnQuickMonthlyReport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdminGenerateReports;
    private javax.swing.JLabel lblCRUDtitle;
    // End of variables declaration//GEN-END:variables
}
