
package hostelmanagementsystem.Admin;

import javax.swing.ImageIcon;

public class ContactUs extends javax.swing.JFrame {

    ImageIcon LPbg = new ImageIcon("landingpage_bg.png");
    ImageIcon wi = new ImageIcon("thelogo.jpg");
    
    public ContactUs() {
        initComponents();
        this.setSize(525, 355);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        BgPic1.setText("");
        BgPic1.setIcon(LPbg);
        
        // Window itself
        this.setTitle("Contact Us | XYZ Hostel Management");
        this.setIconImage(wi.getImage());
        
        // Window when close
        this.setDefaultCloseOperation(LandingPage.EXIT_ON_CLOSE);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BackClick = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BgPic1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 192, 244));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(490, 0, 50, 370);

        BackClick.setFont(new java.awt.Font("Kanit SemiBold", 0, 14)); // NOI18N
        BackClick.setForeground(new java.awt.Color(255, 255, 255));
        BackClick.setText("<< BACK");
        BackClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackClickMouseClicked(evt);
            }
        });
        getContentPane().add(BackClick);
        BackClick.setBounds(20, 20, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\Documents\\NetBeansProjects\\HostelManagementSystem\\website_icon.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 210, 50, 50);

        jLabel3.setFont(new java.awt.Font("Kanit SemiBold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("contact@xyzh.com");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 210, 350, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\Documents\\NetBeansProjects\\HostelManagementSystem\\website_icon.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 120, 50, 50);

        jLabel4.setFont(new java.awt.Font("Kanit SemiBold", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CONTACT US");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 40, 230, 40);

        jLabel5.setFont(new java.awt.Font("Kanit SemiBold", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("xyzhostel.com.my");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 120, 310, 40);

        BgPic1.setToolTipText("XYZ hostel background");
        BgPic1.setMinimumSize(new java.awt.Dimension(500, 350));
        BgPic1.setName("BgPic1"); // NOI18N
        BgPic1.setPreferredSize(new java.awt.Dimension(500, 350));
        getContentPane().add(BgPic1);
        BgPic1.setBounds(0, 0, 570, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackClickMouseClicked
        LandingPage lp = new LandingPage();
        lp.setLocationRelativeTo(null);
        lp.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackClickMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackClick;
    private javax.swing.JLabel BgPic1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
