/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostelmanagementsystem.Admin;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Daniel
 */
public class ForgotPassword extends javax.swing.JFrame {

    ImageIcon abg = new ImageIcon("forgotpass_bg.jpg");
    ImageIcon wi = new ImageIcon("thelogo.jpg");

    /**
     * Creates new form AdminLogin
     */
    public ForgotPassword() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        ForgotPassBg.setText("");
        ForgotPassBg.setIcon(abg);

        this.setLocationRelativeTo(null);
        this.setResizable(false);

        // Window itself
        this.setTitle("Admin Login | XYZ Hostel Management");
        this.setSize(800, 550);

        //Window itself
        this.setIconImage(wi.getImage());

        // Window when close
        this.setDefaultCloseOperation(LandingPage.EXIT_ON_CLOSE);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtUsernameFP = new javax.swing.JTextField();
        BgPic1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtConfirmPasswordFP = new javax.swing.JTextField();
        btnResetFP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNewPasswordFP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnForgotPassSubmit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jpfSecretPinFP = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        BackBtn = new javax.swing.JButton();
        ForgotPassBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(19, 139, 221));
        setForeground(new java.awt.Color(19, 139, 221));
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(102, 192, 244));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 495, 810, 90);

        jPanel2.setBackground(new java.awt.Color(45, 78, 98));
        jPanel2.setLayout(null);

        txtUsernameFP.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtUsernameFP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtUsernameFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameFPActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsernameFP);
        txtUsernameFP.setBounds(230, 170, 190, 40);
        jPanel2.add(BgPic1);
        BgPic1.setBounds(40, 70, 60, 60);

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(91, 196, 255));
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 290, 150, 0);

        jLabel5.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(67, 218, 218));
        jLabel5.setText("_____________________________________");
        jLabel5.setToolTipText("");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 20, 340, 60);

        jLabel6.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("ADMIN LOGIN");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(180, 70, 90, 20);

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("_________________________________");
        jLabel7.setToolTipText("");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 100, 330, 60);

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("FORGOT PASS");
        jLabel8.setToolTipText("");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(110, 80, 230, 60);

        jLabel9.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("_____________________________________");
        jLabel9.setToolTipText("");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(40, 100, 340, 60);

        txtConfirmPasswordFP.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtConfirmPasswordFP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtConfirmPasswordFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPasswordFPActionPerformed(evt);
            }
        });
        jPanel2.add(txtConfirmPasswordFP);
        txtConfirmPasswordFP.setBounds(230, 290, 190, 40);

        btnResetFP.setFont(new java.awt.Font("Kanit SemiBold", 3, 18)); // NOI18N
        btnResetFP.setText("RESET");
        btnResetFP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnResetFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetFPActionPerformed(evt);
            }
        });
        jPanel2.add(btnResetFP);
        btnResetFP.setBounds(40, 420, 170, 60);
        btnResetFP.getAccessibleContext().setAccessibleName("");

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(91, 196, 255));
        jLabel2.setText("USERNAME:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(100, 170, 100, 32);

        txtNewPasswordFP.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtNewPasswordFP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNewPasswordFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPasswordFPActionPerformed(evt);
            }
        });
        jPanel2.add(txtNewPasswordFP);
        txtNewPasswordFP.setBounds(230, 230, 190, 40);

        jLabel10.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(91, 196, 255));
        jLabel10.setText("CONFIRM PASSWORD:");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 290, 190, 32);

        jLabel11.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(91, 196, 255));
        jLabel11.setText("NEW PASSWORD:");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel11);
        jLabel11.setBounds(60, 230, 150, 32);

        btnForgotPassSubmit.setFont(new java.awt.Font("Kanit SemiBold", 3, 18)); // NOI18N
        btnForgotPassSubmit.setText("SUBMIT");
        btnForgotPassSubmit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnForgotPassSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotPassSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(btnForgotPassSubmit);
        btnForgotPassSubmit.setBounds(240, 420, 170, 60);

        jLabel12.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(91, 196, 255));
        jLabel12.setText("SECRET PIN:");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel12);
        jLabel12.setBounds(100, 350, 110, 32);

        jpfSecretPinFP.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jpfSecretPinFP.setToolTipText("Ener Your Pin");
        jpfSecretPinFP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpfSecretPinFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfSecretPinFPActionPerformed(evt);
            }
        });
        jPanel2.add(jpfSecretPinFP);
        jpfSecretPinFP.setBounds(230, 350, 190, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, -10, 450, 570);

        jPanel1.setBackground(new java.awt.Color(27, 40, 56));
        jPanel1.setLayout(null);

        BackBtn.setFont(new java.awt.Font("Kanit Medium", 2, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn);
        BackBtn.setBounds(230, 20, 100, 40);

        ForgotPassBg.setToolTipText("");
        jPanel1.add(ForgotPassBg);
        ForgotPassBg.setBounds(0, -10, 380, 580);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(450, 0, 360, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameFPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameFPActionPerformed

    private void btnResetFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetFPActionPerformed
        // CRUD side
        txtUsernameFP.setText("");
        txtNewPasswordFP.setText("");
        txtConfirmPasswordFP.setText("");
        jpfSecretPinFP.setText("");
    }//GEN-LAST:event_btnResetFPActionPerformed

    private void txtConfirmPasswordFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPasswordFPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPasswordFPActionPerformed

    private void txtNewPasswordFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPasswordFPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPasswordFPActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        AdminLogin al = new AdminLogin();
        al.setLocationRelativeTo(null);
        al.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackBtnActionPerformed

    private int failedAttempts = 0;
    private Timer timer;
    private final SecretPin secretPinInstance = new SecretPin();


    private void btnForgotPassSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotPassSubmitActionPerformed
        String username = txtUsernameFP.getText();
        String newPassword = txtNewPasswordFP.getText();
        String confirmPassword = txtConfirmPasswordFP.getText();
        char[] passwordChars = jpfSecretPinFP.getPassword();
        String secretPin = new String(passwordChars);

        try {
            if (newPassword.equals(confirmPassword) && secretPin.equals(secretPinInstance.getSecretPinValue())) {
                File adminDbFile = new File("admin_database.txt");
                String adminData;
                try ( Scanner fps = new Scanner(adminDbFile)) {
                    fps.useDelimiter("[,]");
                    adminData = "";
                    while (fps.hasNextLine()) {
                        String usernameDb = fps.next();
                        String passwordDb = fps.next();

                        if (username.equals(usernameDb.trim())) {
                            // Update the password for the matching admin
                            adminData += usernameDb + "," + newPassword + "\n";
                        } else {
                            adminData += usernameDb + "," + passwordDb + "\n";
                        }
                    }
                }

                try ( BufferedWriter writer = new BufferedWriter(new FileWriter(adminDbFile))) {
                    writer.write(adminData);
                }

                JOptionPane.showMessageDialog(null, "Password updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                AdminLogin al = new AdminLogin();
                al.setLocationRelativeTo(null);
                al.setVisible(true);
                this.dispose();
            } else {
                failedAttempts++;
                if (failedAttempts == 3) {
                    btnForgotPassSubmit.setEnabled(false);
                    timer = new Timer(10 * 60 * 1000, new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            btnForgotPassSubmit.setEnabled(true);
                            failedAttempts = 0;
                            timer.stop();
                        }
                    });
                    timer.start();
                    JOptionPane.showMessageDialog(null, "Invalid input! Please try again after 10 minutes.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid input! Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error accessing secret pin or updating password.", "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnForgotPassSubmitActionPerformed

    private void jpfSecretPinFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfSecretPinFPActionPerformed

    }//GEN-LAST:event_jpfSecretPinFPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel BgPic1;
    private javax.swing.JLabel ForgotPassBg;
    private javax.swing.JButton btnForgotPassSubmit;
    private javax.swing.JButton btnResetFP;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jpfSecretPinFP;
    private javax.swing.JTextField txtConfirmPasswordFP;
    private javax.swing.JTextField txtNewPasswordFP;
    private javax.swing.JTextField txtUsernameFP;
    // End of variables declaration//GEN-END:variables
}
