package hostelmanagementsystem.Admin;

import hostelmanagementsystem.Students.LoginForm;
import javax.swing.ImageIcon;

public class LandingPage extends javax.swing.JFrame {
    
    private UserSession userSession;
    
    ImageIcon LPbg = new ImageIcon("landingpage_bg.png");
    ImageIcon wi = new ImageIcon("thelogo.jpg");
                
    public LandingPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        BgPic1.setText("");
        BgPic1.setIcon(LPbg);
        
        
        //Window itself
        this.setIconImage(wi.getImage());
        
        // Window when close
       this.setDefaultCloseOperation(LandingPage.EXIT_ON_CLOSE);
       this.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ExitClick = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JButton();
        StudentBtn = new javax.swing.JButton();
        AdminBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        AboutUsClick = new javax.swing.JLabel();
        ContactUsClick = new javax.swing.JLabel();
        BgPic1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("XYZ Hostel Landing Page");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 228, 181));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 425, 810, 75);

        jPanel2.setBackground(new java.awt.Color(255, 250, 205));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 420, 810, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\Documents\\NetBeansProjects\\HostelManagementSystem\\XYZ_small.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 30, 188, 70);

        ExitClick.setFont(new java.awt.Font("Kanit SemiBold", 0, 14)); // NOI18N
        ExitClick.setForeground(new java.awt.Color(255, 255, 255));
        ExitClick.setText(">> EXIT");
        ExitClick.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ExitClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitClickMouseClicked(evt);
            }
        });
        getContentPane().add(ExitClick);
        ExitClick.setBounds(720, 20, 60, 30);

        ExitBtn.setFont(new java.awt.Font("Kanit Medium", 2, 18)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ExitBtn);
        ExitBtn.setBounds(560, 250, 170, 60);

        StudentBtn.setFont(new java.awt.Font("Kanit Medium", 2, 18)); // NOI18N
        StudentBtn.setText("Student");
        StudentBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        StudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(StudentBtn);
        StudentBtn.setBounds(70, 250, 170, 60);

        AdminBtn.setFont(new java.awt.Font("Kanit Medium", 2, 18)); // NOI18N
        AdminBtn.setText("Admin");
        AdminBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        AdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AdminBtn);
        AdminBtn.setBounds(310, 250, 170, 60);

        jLabel3.setFont(new java.awt.Font("Kanit SemiBold", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("WELCOME TO XYZ HOSTEL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 100, 590, 99);

        AboutUsClick.setFont(new java.awt.Font("Kanit SemiBold", 0, 14)); // NOI18N
        AboutUsClick.setForeground(new java.awt.Color(255, 255, 255));
        AboutUsClick.setText("| ABOUT US |");
        AboutUsClick.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        AboutUsClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutUsClickMouseClicked(evt);
            }
        });
        getContentPane().add(AboutUsClick);
        AboutUsClick.setBounds(370, 30, 90, 30);

        ContactUsClick.setFont(new java.awt.Font("Kanit SemiBold", 0, 14)); // NOI18N
        ContactUsClick.setForeground(new java.awt.Color(255, 255, 255));
        ContactUsClick.setText("| CONTACT US |");
        ContactUsClick.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ContactUsClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactUsClickMouseClicked(evt);
            }
        });
        getContentPane().add(ContactUsClick);
        ContactUsClick.setBounds(490, 30, 100, 30);

        BgPic1.setToolTipText("XYZ hostel background");
        BgPic1.setName("BgPic1"); // NOI18N
        BgPic1.setPreferredSize(new java.awt.Dimension(805, 495));
        getContentPane().add(BgPic1);
        BgPic1.setBounds(0, 0, 810, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentBtnActionPerformed
        LoginForm sl = new LoginForm(userSession);
        sl.show();
        this.dispose();
    }//GEN-LAST:event_StudentBtnActionPerformed
        
    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void AdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBtnActionPerformed
        AdminLogin al = new AdminLogin() {};
        al.setLocationRelativeTo(null); 
        al.setVisible(true);
        dispose();
    }//GEN-LAST:event_AdminBtnActionPerformed

    private void AboutUsClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsClickMouseClicked
       AboutUs au = new AboutUs();
       au.setLocationRelativeTo(null);
       au.setVisible(true);
       dispose();
    }//GEN-LAST:event_AboutUsClickMouseClicked

    private void ContactUsClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactUsClickMouseClicked
        ContactUs cu = new ContactUs();
        cu.setLocationRelativeTo(null);
        cu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ContactUsClickMouseClicked

    private void ExitClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitClickMouseClicked
        System.exit(0);
        
    }//GEN-LAST:event_ExitClickMouseClicked
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutUsClick;
    private javax.swing.JButton AdminBtn;
    private javax.swing.JLabel BgPic1;
    private javax.swing.JLabel ContactUsClick;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JLabel ExitClick;
    private javax.swing.JButton StudentBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
