/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostelmanagementsystem.Admin;

import java.io.File;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class QuickMonthReport extends javax.swing.JFrame {

    private UserSession userSession;

    ImageIcon wi = new ImageIcon("thelogo.jpg");

    /**
     * Creates new form QuickMonthReport
     */
    public QuickMonthReport(UserSession userSession) {

        //Define User Session
        this.userSession = userSession;

        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);

        this.setSize(833, 545);

        //Window itself
        this.setIconImage(wi.getImage());
        this.setTitle("Admin Quick Monthly Report | XYZ Hostel Management");

        // Window when close
        this.setDefaultCloseOperation(LandingPage.EXIT_ON_CLOSE);
        this.setVisible(false);

        DefaultTableModel model = (DefaultTableModel) tableQMR.getModel();
        model.setColumnCount(0); // Clear existing columns
        model.setRowCount(0); // Clear existing rows

        // Add the desired columns to the table model
        model.addColumn("Room ID");
        model.addColumn("Room Type");
        model.addColumn("Room Price");
        model.addColumn("Status");

        // read the data from FormSub.txt and populate the table model
        try {
            // read the data from FormSub.txt
            Scanner s3 = new Scanner(new File("C:\\Users\\danie\\Documents\\NetBeansProjects\\HostelManagementSystem\\FormSub.txt"));

            // Iterate through each line of the file
            while (s3.hasNextLine()) {
                String line = s3.nextLine();
                if (line.contains("|")) {
                    String[] data = line.split("\\|");

                    // Extract the required data fields
                    String roomID = data[10];
                    String roomType = data[11];
                    double roomPrice = Double.parseDouble(data[12].replaceAll("RM", ""));
                    String status = data[13];

                    // Add a row to the table model
                    model.addRow(new Object[]{roomID, roomType, roomPrice, status});

                    int rowCount = model.getRowCount();
                    double totalRoomPrice = 0;

                    // Calculate the total room price
                    for (int i = 0; i < rowCount; i++) {
                        roomPrice = (double) model.getValueAt(i, 2);
                        totalRoomPrice += roomPrice;
                    }

                    double averageRoomPrice = totalRoomPrice / rowCount;

                    // Display the calculated values
                    txtTotalRoomPrice.setText("RM " + String.valueOf(totalRoomPrice));
                    txtAverageRoomPrice.setText("RM " + String.valueOf(averageRoomPrice));
                    txtTotalApplications.setText(String.valueOf(rowCount));
                }
            }

            s3.close();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableQMR = new javax.swing.JTable();
        lblCRUDtitle = new javax.swing.JLabel();
        btnBackAGR = new javax.swing.JButton();
        lblCRUDtitle1 = new javax.swing.JLabel();
        lblCRUDtitle2 = new javax.swing.JLabel();
        lblCRUDtitle3 = new javax.swing.JLabel();
        txtTotalRoomPrice = new javax.swing.JTextField();
        txtTotalApplications = new javax.swing.JTextField();
        txtAverageRoomPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(42, 71, 94));
        jPanel1.setForeground(new java.awt.Color(27, 40, 56));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        tableQMR.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        tableQMR.setForeground(new java.awt.Color(27, 40, 56));
        tableQMR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room ID", "Room Type", "Room Price", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableQMR.setToolTipText("This table will display all the room info based on the admin inout.");
        tableQMR.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableQMR.setEnabled(false);
        tableQMR.setRowHeight(30);
        tableQMR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableQMRMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableQMR);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 110, 760, 280);

        lblCRUDtitle.setFont(new java.awt.Font("Kanit SemiBold", 0, 24)); // NOI18N
        lblCRUDtitle.setForeground(new java.awt.Color(255, 255, 255));
        lblCRUDtitle.setText("Quick Monthly Report");
        lblCRUDtitle.setName("AdminHRI"); // NOI18N
        jPanel1.add(lblCRUDtitle);
        lblCRUDtitle.setBounds(300, 60, 250, 30);

        btnBackAGR.setFont(new java.awt.Font("Kanit Medium", 2, 18)); // NOI18N
        btnBackAGR.setText("Back");
        btnBackAGR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackAGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAGRActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackAGR);
        btnBackAGR.setBounds(30, 50, 130, 40);

        lblCRUDtitle1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        lblCRUDtitle1.setForeground(new java.awt.Color(242, 244, 245));
        lblCRUDtitle1.setText("TOTAL APPLICATION:");
        lblCRUDtitle1.setName("AdminHRI"); // NOI18N
        jPanel1.add(lblCRUDtitle1);
        lblCRUDtitle1.setBounds(570, 420, 180, 30);

        lblCRUDtitle2.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        lblCRUDtitle2.setForeground(new java.awt.Color(242, 244, 245));
        lblCRUDtitle2.setText("AVERAGE  ROOM PRICE:");
        lblCRUDtitle2.setName("AdminHRI"); // NOI18N
        jPanel1.add(lblCRUDtitle2);
        lblCRUDtitle2.setBounds(30, 420, 210, 30);

        lblCRUDtitle3.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        lblCRUDtitle3.setForeground(new java.awt.Color(242, 244, 245));
        lblCRUDtitle3.setText("TOTAL MONTHLY PRICE:");
        lblCRUDtitle3.setName("AdminHRI"); // NOI18N
        jPanel1.add(lblCRUDtitle3);
        lblCRUDtitle3.setBounds(20, 480, 210, 30);

        txtTotalRoomPrice.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtTotalRoomPrice.setForeground(new java.awt.Color(0, 51, 153));
        txtTotalRoomPrice.setToolTipText("Enter Your Usernme");
        txtTotalRoomPrice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTotalRoomPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalRoomPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalRoomPrice);
        txtTotalRoomPrice.setBounds(250, 480, 190, 40);

        txtTotalApplications.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtTotalApplications.setForeground(new java.awt.Color(0, 51, 153));
        txtTotalApplications.setToolTipText("Enter Your Usernme");
        txtTotalApplications.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTotalApplications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalApplicationsActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalApplications);
        txtTotalApplications.setBounds(570, 460, 190, 40);

        txtAverageRoomPrice.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtAverageRoomPrice.setForeground(new java.awt.Color(0, 51, 153));
        txtAverageRoomPrice.setToolTipText("Enter Your Usernme");
        txtAverageRoomPrice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtAverageRoomPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAverageRoomPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtAverageRoomPrice);
        txtAverageRoomPrice.setBounds(250, 420, 190, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -30, 910, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableQMRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableQMRMouseClicked

    }//GEN-LAST:event_tableQMRMouseClicked

    private void btnBackAGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAGRActionPerformed
        AdminGenerateReports agr = new AdminGenerateReports(userSession); // Pass the UserSession instance
        agr.setLocationRelativeTo(null);
        agr.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackAGRActionPerformed

    private void txtTotalRoomPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalRoomPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalRoomPriceActionPerformed

    private void txtTotalApplicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalApplicationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalApplicationsActionPerformed

    private void txtAverageRoomPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAverageRoomPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAverageRoomPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuickMonthReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuickMonthReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuickMonthReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuickMonthReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserSession userSession = new UserSession("admin"); // Create UserSession instance with username
                new QuickMonthReport(userSession).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackAGR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCRUDtitle;
    private javax.swing.JLabel lblCRUDtitle1;
    private javax.swing.JLabel lblCRUDtitle2;
    private javax.swing.JLabel lblCRUDtitle3;
    private javax.swing.JTable tableQMR;
    private javax.swing.JTextField txtAverageRoomPrice;
    private javax.swing.JTextField txtTotalApplications;
    private javax.swing.JTextField txtTotalRoomPrice;
    // End of variables declaration//GEN-END:variables
}
