/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostelmanagementsystem.Students;

import hostelmanagementsystem.Admin.FilesLocation;
import hostelmanagementsystem.Admin.LandingPage;
import hostelmanagementsystem.Admin.UserSession;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.util.Date;
import hostelmanagementsystem.Students.Payment;
import javax.swing.ImageIcon;

/**
 *
 * @author Killi
 */
public class HostelApplicationForm extends javax.swing.JFrame implements FilesLocation {

    ImageIcon wi = new ImageIcon("thelogo.jpg");

    private UserSession userSession;
    int in;
    String ID, Name, Course, Email, Intake, Age, Address, Status, RoomNo, RoomType, RoomPrice;

    public HostelApplicationForm(UserSession userSession) {

        //Define User Session
        this.userSession = userSession;

        initComponents();

        this.setLocationRelativeTo(null);
        this.setResizable(false);

        // Window itself
        this.setIconImage(wi.getImage());
        this.setTitle("Student Hostel Application Form Page | XYZ Hostel");

        // Window when close
        this.setDefaultCloseOperation(LandingPage.EXIT_ON_CLOSE);
        this.setVisible(false);
        cbRoomNumber.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String selectedRoomID = (String) cbRoomNumber.getSelectedItem();
                importData(selectedRoomID);
            }
        });
    }

    void readFile() {
        File formFile = new File(FORMSUB_FILE_PATH);
        if (formFile.exists()) {
            System.err.println("File exists!");
        } else {
            try {
                formFile.createNewFile();
                System.out.println("File created");
            } catch (IOException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    void importData(String roomID) {
        try ( FileReader fr = new FileReader(ROOM_DETAILS_FILE_PATH);  BufferedReader br = new BufferedReader(fr)) {
            String line;
            String specificColumn1 = "";
            String specificColumn2 = "";

            // Loop through the lines in the text file
            while ((line = br.readLine()) != null) {
                String[] columns = line.split(",");

                String currentRoomID = columns[0];

                if (currentRoomID.equals(roomID)) {
                    specificColumn1 = columns[1].trim(); // Room Type
                    specificColumn2 = columns[4].trim(); // Room Price

                    // Exit the loop since the desired room ID is found
                    break;
                }
            }

            TXT2.setText(specificColumn1);
            TXT1.setText(specificColumn2);

        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String[] getDataFromForm1() {
        String[] formData = new String[9];
        formData[0] = J1.getText();
        formData[1] = J2.getText();
        formData[2] = J3.getText();
        formData[3] = J4.getText();
        formData[4] = J5.getText();
        formData[5] = J6.getText();
        formData[6] = cbRoomNumber.getSelectedItem().toString();
        formData[7] = TXT1.getText();
        formData[8] = TXT2.getText();

        return formData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        J5 = new javax.swing.JTextField();
        J1 = new javax.swing.JTextField();
        J2 = new javax.swing.JTextField();
        J6 = new javax.swing.JTextField();
        J3 = new javax.swing.JTextField();
        J4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtBackSD = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbRoomNumber = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        TXT1 = new javax.swing.JTextField();
        TXT2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 480));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Student Name:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 110, 100, 30);

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Intake:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 320, 90, 24);

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Age:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 180, 90, 24);

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Course:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 250, 90, 24);

        jLabel5.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Email:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(480, 100, 80, 16);

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("Room Number:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(440, 220, 170, 24);

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 255));
        jLabel7.setText("Address:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(470, 160, 80, 24);
        jPanel1.add(J5);
        J5.setBounds(550, 150, 200, 40);
        jPanel1.add(J1);
        J1.setBounds(170, 110, 200, 40);
        jPanel1.add(J2);
        J2.setBounds(170, 240, 200, 40);
        jPanel1.add(J6);
        J6.setBounds(170, 170, 200, 40);
        jPanel1.add(J3);
        J3.setBounds(550, 90, 200, 40);
        jPanel1.add(J4);
        J4.setBounds(170, 310, 200, 40);

        jButton1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(630, 400, 130, 50);

        txtBackSD.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtBackSD.setText("Return Back");
        txtBackSD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBackSDMouseClicked(evt);
            }
        });
        txtBackSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBackSDActionPerformed(evt);
            }
        });
        jPanel1.add(txtBackSD);
        txtBackSD.setBounds(40, 400, 150, 50);

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setText("Room Type:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(450, 280, 80, 16);

        cbRoomNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HR1", "HR2", "HR3", "HR4", "HR5", "HR6", "HR7", "HR8" }));
        cbRoomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoomNumberActionPerformed(evt);
            }
        });
        jPanel1.add(cbRoomNumber);
        cbRoomNumber.setBounds(550, 210, 200, 40);

        jLabel13.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 255));
        jLabel13.setText("Room Price:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(450, 340, 120, 16);
        jPanel1.add(TXT1);
        TXT1.setBounds(550, 330, 200, 40);

        TXT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT2ActionPerformed(evt);
            }
        });
        jPanel1.add(TXT2);
        TXT2.setBounds(550, 270, 200, 40);

        jLabel9.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Student Application Form");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 10, 420, 70);

        btnNext.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        btnNext.setText("Next");
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel1.add(btnNext);
        btnNext.setBounds(470, 400, 130, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBackSDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBackSDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBackSDMouseClicked

    private void txtBackSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBackSDActionPerformed
        StudentDashboard sd = new StudentDashboard(userSession);
        sd.setLocationRelativeTo(null);
        sd.setVisible(true);
        sd.setResizable(false);

        dispose();
    }//GEN-LAST:event_txtBackSDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        J1.setText("");
        J2.setText("");
        J3.setText("");
        J4.setText("");
        J5.setText("");
        J6.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbRoomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoomNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRoomNumberActionPerformed

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextMouseClicked

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        ID = J1.getText();
        Course = J2.getText();
        Email = J3.getText();
        Intake = J4.getText();
        Age = J6.getText();
        Address = J5.getText();
        RoomNo = cbRoomNumber.getSelectedItem().toString();
        RoomType = TXT2.getText();
        RoomPrice = TXT1.getText();
        String[] formData = getDataFromForm1();

        readFile();

        if (ID.equals("")) {
            JOptionPane.showMessageDialog(null, "Name is mandatory.");
        } else if (Course.equals("")) {
            JOptionPane.showMessageDialog(null, "Course is mandatory.");
        } else if (Email.equals("")) {
            JOptionPane.showMessageDialog(null, "Email is mandatory.");
        } else if (Intake.equals("")) {
            JOptionPane.showMessageDialog(null, "Intake is mandatory.");
        } else if (Age.equals("")) {
            JOptionPane.showMessageDialog(null, "Age is mandatory.");
        } else if (Address.equals("")) {
            JOptionPane.showMessageDialog(null, "Address is mandatory.");
        } else if (!Age.matches("\\d+")) {
            // Validate the age field using regex to ensure it contains only digits
            JOptionPane.showMessageDialog(null, "Invalid age. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!Email.matches("[\\w.]+@[\\w.]+\\.\\w+")) {
            // Validate the email field using regex to ensure it has a valid email format
            JOptionPane.showMessageDialog(null, "Invalid email address. Please enter a valid email.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (Address.length() < 5) {
            // Validate the address field to ensure it has a minimum length of 5 characters
            JOptionPane.showMessageDialog(null, "Invalid address. Please enter a valid address.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!Course.matches("[A-Za-z\\s]+")) {
            // Validate the course field using regex to ensure it contains only alphabets and spaces
            JOptionPane.showMessageDialog(null, "Invalid course name. Please enter a valid course.", "Error", JOptionPane.ERROR_MESSAGE);
            // Validate the course field using regex to ensure it contains only alphabets and spaces
            JOptionPane.showMessageDialog(this, "Invalid course name. Please enter a valid course.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Payment paymentForm = new Payment(formData);
            paymentForm.setVisible(true);
            this.dispose();
            JOptionPane.showMessageDialog(this, "Submitted! Please continue to payment.");
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void TXT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HostelApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HostelApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HostelApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HostelApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserSession userSession = new UserSession("student"); 
                new HostelApplicationForm(userSession).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField J1;
    private javax.swing.JTextField J2;
    private javax.swing.JTextField J3;
    private javax.swing.JTextField J4;
    private javax.swing.JTextField J5;
    private javax.swing.JTextField J6;
    private javax.swing.JTextField TXT1;
    private javax.swing.JTextField TXT2;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<String> cbRoomNumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton txtBackSD;
    // End of variables declaration//GEN-END:variables
}
