/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostelmanagementsystem.Students;

import hostelmanagementsystem.Admin.FilesLocation;
import hostelmanagementsystem.Admin.LandingPage;
import hostelmanagementsystem.Admin.UserSession;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import hostelmanagementsystem.Students.Registration;
import java.io.BufferedWriter;
import java.util.HashMap;
import java.util.Map;
import java.io.*;
import javax.swing.ImageIcon;

/**
 *
 * @author Killi
 */
public class LoginForm extends javax.swing.JFrame implements FilesLocation {

    int in;
    private Map<String, String> loginData;
    private UserSession userSession;
    
    ImageIcon wi = new ImageIcon("thelogo.jpg");

    /**
     * Creates new form LoginForm
     */
    public LoginForm(UserSession userSession) {

        //Define User Session
        this.userSession = userSession;

        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        readFile();

        //Window itself
        this.setIconImage(wi.getImage());
        this.setTitle("Student Login | XYZ Hostel");

        // Window when close
        this.setDefaultCloseOperation(Registration.EXIT_ON_CLOSE);
        this.setVisible(false);
    }

    private void readFile() {
        loginData = new HashMap<>();

        try ( BufferedReader reader = new BufferedReader(new FileReader(LOGIN_FILE_PATH))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] data = line.split("\\|");
                if (data.length == 2) {
                    String username = data[0];
                    String password = data[1];
                    loginData.put(username, password);
                }
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    private void checkData(String username, String password) {
        if (loginData.containsKey(username)) {
            String storedPassword = loginData.get(username);
            if (password.equals(storedPassword)) {
                JOptionPane.showMessageDialog(null, "Password Matched");
                StudentDashboard DBl = new StudentDashboard(userSession);
                DBl.setVisible(true);
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Invalid User/Password");
    }

    private void countLines() {
        try ( RandomAccessFile raf = new RandomAccessFile(LOGIN_FILE_PATH, "rw")) {
            int lines = 0;
            String line;
            while ((line = raf.readLine()) != null) {
                lines++;
            }
            System.out.println("Number of lines: " + lines);
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    private void logic(String username, String password) {
        if (loginData.containsKey(username)) {
            String storedPassword = loginData.get(username);
            if (password.equals(storedPassword)) {
                JOptionPane.showMessageDialog(null, "Password Matched");
                StudentDashboard DBl = new StudentDashboard(userSession);
                DBl.setVisible(true);
                this.setVisible(false);
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Incorrect Username/Password");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBckLP = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tfuser = new javax.swing.JTextField();
        tfpswd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Login | XYZ Hostel ");
        setBackground(new java.awt.Color(0, 102, 204));
        setMinimumSize(new java.awt.Dimension(943, 575));
        setSize(new java.awt.Dimension(800, 480));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(943, 0, 0, 0);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 480));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 480));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 480));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagementsystem/Students/463271_16091517490046512024_1024x682_1_386x412.jpg"))); // NOI18N
        jLabel1.setName(""); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 100, 386, 386);

        btnBckLP.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        btnBckLP.setText("Back");
        btnBckLP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBckLPActionPerformed(evt);
            }
        });
        jPanel2.add(btnBckLP);
        btnBckLP.setBounds(20, 20, 110, 40);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setForeground(new java.awt.Color(51, 102, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        tfuser.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        tfuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuserActionPerformed(evt);
            }
        });
        jPanel1.add(tfuser);
        tfuser.setBounds(170, 40, 160, 40);

        tfpswd.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jPanel1.add(tfpswd);
        tfpswd.setBounds(170, 90, 160, 40);

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 204, 255));
        jLabel3.setText("StudentID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 40, 100, 32);

        jLabel4.setBackground(new java.awt.Color(153, 204, 255));
        jLabel4.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 204, 255));
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 90, 100, 32);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(480, 140, 370, 160);

        jButton2.setBackground(new java.awt.Color(27, 40, 56));
        jButton2.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(480, 330, 180, 60);

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("STUDENT LOGIN ");
        jLabel2.setAlignmentX(0.5F);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(480, 80, 390, 40);

        jButton4.setBackground(new java.awt.Color(27, 40, 56));
        jButton4.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Register");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(680, 330, 170, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-4, -4, 990, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBckLPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBckLPActionPerformed
        LandingPage lp = new LandingPage();
        lp.show();
        this.dispose();
    }//GEN-LAST:event_btnBckLPActionPerformed

    private void tfuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuserActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        createFolder();
        readFile();
        countLines();
        logic(tfuser.getText(), tfpswd.getText());
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Registration Sel = new Registration(userSession);
        Sel.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 UserSession userSession = new UserSession("student"); 
                new LoginForm(userSession).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBckLP;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfpswd;
    private javax.swing.JTextField tfuser;
    // End of variables declaration//GEN-END:variables
}
