/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostelmanagementsystem.Students;

import hostelmanagementsystem.Admin.AdminMainMenu;
import hostelmanagementsystem.Admin.FilesLocation;
import hostelmanagementsystem.Admin.LandingPage;
import hostelmanagementsystem.Admin.UserSession;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManagerSAP extends javax.swing.JFrame implements FilesLocation {

    ImageIcon wi = new ImageIcon("thelogo.jpg");
    private UserSession userSession;

    /**
     * Creates new form ManageStudentApplicationStatusPage
     */
    public ManagerSAP(UserSession userSession) {
        initComponents();
        
       
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        importData();
        
        

        //Define User Session
        this.userSession = userSession;

        //Window itself
        this.setSize(1433, 662);
        this.setIconImage(wi.getImage());
        this.setTitle("Admin CRUD HRI | XYZ Hostel Management");

        // Window when close
        this.setDefaultCloseOperation(LandingPage.EXIT_ON_CLOSE);
        this.setVisible(false);

    }

    private void importData() {
        try ( BufferedReader br = new BufferedReader(new FileReader(FORMSUB_FILE_PATH))) {
            String line;
            DefaultTableModel model = (DefaultTableModel) TableSHAM.getModel();
            while ((line = br.readLine()) != null) {
                String[] data = line.split("\\|");
                model.addRow(data);
            }
        } catch (IOException ex) {
            Logger.getLogger(ManagerSAP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void updateData() {
        String newStatus = jComboBox2.getSelectedItem().toString();
        int row = TableSHAM.getSelectedRow();
        String studentIDSelected = TableSHAM.getModel().getValueAt(row, 0).toString();
        ArrayList<String> temp = new ArrayList<>();

        try ( BufferedReader br = new BufferedReader(new FileReader(FORMSUB_FILE_PATH))) {
            String information;
            while ((information = br.readLine()) != null) {
                String[] data = information.split("\\|");
                if (data[0].equals(studentIDSelected)) {
                    data[13] = newStatus;
                    information = String.join("|", data);
                }
                temp.add(information);
            }
        } catch (IOException ex) {
            Logger.getLogger(ManagerSAP.class.getName()).log(Level.SEVERE, null, ex);
        }

        try ( PrintWriter pw = new PrintWriter(new BufferedWriter(new FileWriter(FORMSUB_FILE_PATH)))) {
            for (String data : temp) {
                pw.println(data);
            }
        } catch (IOException ex) {
            Logger.getLogger(ManagerSAP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSHAM = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBackAMM = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 192, 244));
        jPanel1.setLayout(null);

        TableSHAM.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        TableSHAM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Age", "Email", "Address", "Course", "Intake", "Zip Code ", "State", "CardNumber", "CVV", "Room Type", "Room Price", "Status", "Date"
            }
        ));
        jScrollPane1.setViewportView(TableSHAM);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 120, 1095, 480);

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Hostel Application Management");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 40, 880, 62);

        btnBackAMM.setFont(new java.awt.Font("Kanit Medium", 2, 18)); // NOI18N
        btnBackAMM.setText("Back");
        btnBackAMM.setToolTipText("Go Back.");
        btnBackAMM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackAMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAMMActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackAMM);
        btnBackAMM.setBounds(1190, 70, 160, 50);

        jPanel2.setBackground(new java.awt.Color(42, 71, 94));
        jPanel2.setForeground(new java.awt.Color(42, 71, 94));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Application Status");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 40, 150, 14);

        jComboBox2.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Approve", "Reject" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(40, 70, 170, 40);

        jButton1.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(40, 130, 170, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(1150, 200, 250, 240);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1450, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String jC1 = jComboBox2.getSelectedItem().toString();
        updateData();// TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel) TableSHAM.getModel();
        table.setRowCount(0);
        importData();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackAMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAMMActionPerformed
        AdminMainMenu amm = new AdminMainMenu(userSession); // Pass the UserSession instance
        amm.setLocationRelativeTo(null);
        amm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackAMMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerSAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerSAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerSAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerSAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserSession userSession = new UserSession("admin"); // Create UserSession instance with username
                new ManagerSAP(userSession).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableSHAM;
    private javax.swing.JButton btnBackAMM;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
