/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostelmanagementsystem.Students;

import hostelmanagementsystem.Admin.StudentHostelRoomInfo;
import hostelmanagementsystem.Admin.UserSession;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Daniel
 */
public class StudentDashboard extends javax.swing.JFrame {

    ImageIcon wi = new ImageIcon("thelogo.jpg");
    private UserSession userSession;

    /**
     * Creates new form StudentDashboard
     */
    public StudentDashboard(UserSession userSession) {
        //Define User Session
        this.userSession = userSession;
        
        initComponents();
        this.setLocationRelativeTo(null);

        // Window itself
        this.setTitle("Admin Main Menu | XYZ Hostel Management");
        this.setIconImage(wi.getImage());
        this.setSize(750, 455);

        // Window when close
        this.setDefaultCloseOperation(StudentDashboard.EXIT_ON_CLOSE);
        this.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAdminGenerateReports = new javax.swing.JLabel();
        btnBackAGR = new javax.swing.JButton();
        btnExitARR = new javax.swing.JButton();
        btnBackAGR1 = new javax.swing.JButton();
        btnBackAGR2 = new javax.swing.JButton();
        btnBackAGR3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 0, 102));
        jPanel1.setForeground(new java.awt.Color(204, 0, 102));
        jPanel1.setLayout(null);

        lblAdminGenerateReports.setFont(new java.awt.Font("Kanit SemiBold", 0, 48)); // NOI18N
        lblAdminGenerateReports.setForeground(new java.awt.Color(255, 102, 204));
        lblAdminGenerateReports.setText("Student Dashboard");
        lblAdminGenerateReports.setName("AdminHRI"); // NOI18N
        jPanel1.add(lblAdminGenerateReports);
        lblAdminGenerateReports.setBounds(170, 42, 440, 60);

        btnBackAGR.setFont(new java.awt.Font("Kanit Medium", 1, 18)); // NOI18N
        btnBackAGR.setText("Apply Hostel Room Application");
        btnBackAGR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackAGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAGRActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackAGR);
        btnBackAGR.setBounds(230, 300, 350, 50);

        btnExitARR.setFont(new java.awt.Font("Kanit Medium", 2, 18)); // NOI18N
        btnExitARR.setText("Exit");
        btnExitARR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExitARR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitARRActionPerformed(evt);
            }
        });
        jPanel1.add(btnExitARR);
        btnExitARR.setBounds(35, 243, 130, 40);

        btnBackAGR1.setFont(new java.awt.Font("Kanit Medium", 2, 18)); // NOI18N
        btnBackAGR1.setText("Logout");
        btnBackAGR1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackAGR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAGR1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackAGR1);
        btnBackAGR1.setBounds(35, 173, 130, 40);

        btnBackAGR2.setFont(new java.awt.Font("Kanit Medium", 1, 18)); // NOI18N
        btnBackAGR2.setText("Check Historical Record");
        btnBackAGR2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackAGR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAGR2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackAGR2);
        btnBackAGR2.setBounds(230, 140, 350, 50);

        btnBackAGR3.setFont(new java.awt.Font("Kanit Medium", 1, 18)); // NOI18N
        btnBackAGR3.setText("Check Hostel Room Information");
        btnBackAGR3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackAGR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAGR3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackAGR3);
        btnBackAGR3.setBounds(230, 220, 350, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 740, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackAGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAGRActionPerformed
        HostelApplicationForm haf = new HostelApplicationForm(userSession);
        haf.setLocationRelativeTo(null);
        haf.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackAGRActionPerformed

    private void btnExitARRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitARRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitARRActionPerformed

    private void btnBackAGR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAGR1ActionPerformed
        LoginForm lf = new LoginForm(userSession);
        lf.setLocationRelativeTo(null);
        lf.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackAGR1ActionPerformed

    private void btnBackAGR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAGR2ActionPerformed
        Menu1 me = new Menu1(userSession);
        me.setLocationRelativeTo(null);
        me.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackAGR2ActionPerformed

    private void btnBackAGR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAGR3ActionPerformed
        try {
            StudentHostelRoomInfo shri = new StudentHostelRoomInfo(userSession);
            shri.setLocationRelativeTo(null);
            shri.setVisible(true);
            dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(StudentDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBackAGR3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserSession userSession = new UserSession("student"); 
                new StudentDashboard(userSession).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackAGR;
    private javax.swing.JButton btnBackAGR1;
    private javax.swing.JButton btnBackAGR2;
    private javax.swing.JButton btnBackAGR3;
    private javax.swing.JButton btnExitARR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdminGenerateReports;
    // End of variables declaration//GEN-END:variables
}
