/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xyzhostelmanagementsystem;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Killi
 */
public class HostelApplicationForm extends javax.swing.JFrame {
File f =new File("C:\\Users\\Killi\\OneDrive\\桌面\\Java Assigment");
int in;
String ID,Course,Email,Intake,Age,Address,Status;

    /**
     * Creates new form HostelApplicationForm
     */
    public HostelApplicationForm() {
        initComponents();
    }
  void readFile(){
        FileReader fr = null;
        try {
            fr = new FileReader(f+"\\FormSub.txt");
            System.err.println("file exists!");
        } catch (FileNotFoundException ex) {
           try{
            FileWriter fw = new FileWriter(f+"\\FormSub.txt");
           System.out.println("File Created");
            } catch (IOException ex1) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
  void addData(){
        try {
            RandomAccessFile raf = new RandomAccessFile(f+"\\FormSub.txt","rw");
            raf.seek(raf.length());
            raf.writeBytes("Name:"+ ID + ",");
            raf.writeBytes("Course:"+ Course + ",");
            raf.writeBytes("Email:"+ Email + ",");
            raf.writeBytes("Intake:"+ Intake + ",");
            raf.writeBytes("Age:"+ Age + ",");
            raf.writeBytes("Address:"+ Address + ",");
            raf.writeBytes("Prefered Room Number:"+ jComboBox1.getSelectedItem().toString() + ",");
            raf.writeBytes("Status:"+ "Pending");
            raf.writeBytes("\r\n");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    
 }
  void countLine(){
        try {
            in=1;
            RandomAccessFile raf = new RandomAccessFile(f +"\\loginC.txt", "rw");
            for(int i=0;raf.readLine()!=null;i++){
                in++;
            }
            System.out.println("number of lines:"+in);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        J5 = new javax.swing.JTextField();
        J1 = new javax.swing.JTextField();
        J2 = new javax.swing.JTextField();
        J6 = new javax.swing.JTextField();
        J3 = new javax.swing.JTextField();
        J4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 480));
        jPanel1.setLayout(null);

        jLabel1.setText("Student Name:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 90, 72, 14);

        jLabel2.setText("Intake:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 340, 35, 14);

        jLabel3.setText("Age:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(520, 100, 23, 14);

        jLabel4.setText("Course:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 180, 38, 14);

        jLabel5.setText("Email:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 250, 28, 14);

        jLabel6.setText("Prefered Room Number:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(420, 230, 116, 14);

        jLabel7.setText("Address:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(482, 170, 43, 14);
        jPanel1.add(J5);
        J5.setBounds(560, 160, 200, 40);
        jPanel1.add(J1);
        J1.setBounds(180, 80, 200, 40);
        jPanel1.add(J2);
        J2.setBounds(180, 160, 200, 40);
        jPanel1.add(J6);
        J6.setBounds(560, 80, 200, 40);
        jPanel1.add(J3);
        J3.setBounds(180, 240, 200, 40);
        jPanel1.add(J4);
        J4.setBounds(180, 330, 200, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(560, 230, 200, 20);

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(590, 320, 130, 50);

        jButton3.setText("Submit Form");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(420, 320, 130, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            // TODO add your handling code here:
ID = J1.getText();
    Course = J2.getText();
    Email = J3.getText();
    Intake = J4.getText();
    Age = J6.getText();
    Address = J5.getText();
    String jC1= jComboBox1.getSelectedItem().toString();
readFile();
addData();
countLine(); 
            if(ID.equals("")) {
    JOptionPane.showMessageDialog(null, "ID is mandatory.");
}

if(Course.equals("")) {
    JOptionPane.showMessageDialog(null, "Course is mandatory.");
}

if(Email.equals("")) {
    JOptionPane.showMessageDialog(null, "Email is mandatory.");
}

if(Intake.equals("")) {
    JOptionPane.showMessageDialog(null, "Intake is mandatory.");
}

if(Age.equals("")) {
    JOptionPane.showMessageDialog(null, "Age is mandatory.");
}

if(Address.equals("")) {
    JOptionPane.showMessageDialog(null, "Address is mandatory.");
}else{
    JOptionPane.showMessageDialog(this,"Form Successfully Submitted!!");
}
    
            
  










    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
J1.setText("");    
J2.setText(""); 
J3.setText(""); 
J4.setText(""); 
J5.setText(""); 
J6.setText(""); 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HostelApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HostelApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HostelApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HostelApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HostelApplicationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField J1;
    private javax.swing.JTextField J2;
    private javax.swing.JTextField J3;
    private javax.swing.JTextField J4;
    private javax.swing.JTextField J5;
    private javax.swing.JTextField J6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
